name: Alpine
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  amd64:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: jirutka/setup-alpine@v1
      with:
        packages: build-base alpine-sdk meson gtk+3.0-dev vala intltool
    - run: |
        meson setup build
        meson compile -C build
      shell: alpine.sh {0}

  extra-architectures:
    runs-on: ubuntu-22.04
    name: ${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        arch: [armv7, aarch64]

    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      with:
        arch: ${{ matrix.arch }}
        distro: alpine_latest
        install: |
          apk update
          apk add build-base alpine-sdk meson gtk+3.0-dev vala intltool
        run: |
          git config --global --add safe.directory "$PWD"
          git submodule init
          git submodule update

          meson setup build
          meson compile -C build
