name: Build
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt update
    - run: sudo apt install meson intltool libgtk-3-dev libglib2.0-dev valac
    - run: meson build
    - run: meson compile -C build

  alpine:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: jirutka/setup-alpine@v1
      with:
        packages: build-base alpine-sdk meson gtk+3.0-dev vala intltool
    - run: |
        meson setup build
        meson compile -C build
      shell: alpine.sh {0}
