name: Ubuntu
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  amd64:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update
    - run: sudo apt install meson intltool libgtk-3-dev libglib2.0-dev valac
    - run: meson setup build
    - run: meson compile -C build

  extra-architectures:
    runs-on: ubuntu-22.04
    name: ${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        arch: [armv7, aarch64, riscv64]

    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      with:
        arch: ${{ matrix.arch }}
        distro: ubuntu22.04
        install: |
          apt-get update -q -y
          apt-get install -q -y git meson intltool libgtk-3-dev libglib2.0-dev valac
        run: |
          git config --global --add safe.directory "$PWD"
          git submodule init
          git submodule update

          meson setup build
          meson compile -C build
